name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches: [ main ]      # ← 開発用ブランチ

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # ① ソース取得
      - uses: actions/checkout@v4

      # ② Hugo をセットアップしてビルド
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
      - run: hugo          # 生成物は ./public

      # ③ public/ を gh-pages ブランチへ push
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
